### PR TITLE
Added russian language

### PR DESCRIPTION
**Pull request by FromSi**
When translating, there were minor problems, but I decided.
Russian language is the second home for the Russian people. :ru: :)

### CODE REVIEW

**Comment by ohmae** [comment]
Thanks!
But I do not understand Russian at all...
Can you tell me how to confirm? I do not even know the Russian title of language selection :sweat_smile: 
And can you tell me what is "minor problems"?

**Comment by FromSi** [comment]
All is well, but not perfect. =)
The main thing is that now there is a Russian for Russian people :D

**Comment by ohmae** [comment]
I set like this. but display still English...
screenshot_1532265100

**Comment by FromSi** [comment]
Did you add the "values-ru" folder? =)

**Comment by ohmae** [comment]
Yes, and cause turned out.
Additional modification was necessary.
```
diff --git a/mobile/build.gradle b/mobile/build.gradle
index 0be8d98..ebfa261 100644
--- a/mobile/build.gradle
+++ b/mobile/build.gradle
@@ -18,7 +18,7 @@ android {
         targetSdkVersion 27
         versionCode versionMajor * 10000 + versionMinor * 100 + versionPatch
         versionName "${versionMajor}.${versionMinor}.${versionPatch}"
-        resConfigs "en", "ja"
+        resConfigs "en", "ja", "ru"
         vectorDrawables.useSupportLibrary = true
         buildConfigField "long", "BUILD_TIME", "${System.currentTimeMillis()}L"
     }
```

**Comment by FromSi** [comment]
good job :+1:

**Comment by ohmae** [comment]
This app was translated into Russian!
Thanks!
screenshot_1532266056

**Comment by FromSi** [comment]
Instead of "ON" you need to insert "ВКЛ". 
The text will look more beautiful. =)

**Comment by ohmae** [comment]
I did it. Is this OK? https://github.com/ohmae/DmsExplorer/commit/9199a6d96e1b301d815a909ac48ff45b4d65f2f3

**Comment by FromSi** [comment]
Ideally

**Pull request merged**
