### PR TITLE
update chinese simplified language 2019/07/23

### PR DESCRIPTION
**Pull request by wwj402**
update chinese simplified language 2019/07/23 base on commit 120d872

### CODE REVIEW

**Comment by ohmae** [comment]
Thanks! It looks good. (I can not understand Chinese at all :sweat_smile: )

**Comment by ohmae** [comment]
I have a question.
You use `values-zh-rCN` but why not use `values-zh`?
I'm sorry if I have a stupid question. I don't know much about Chinese,

**Comment by wwj402** [comment]
values-zh-rCN for Chinese(simplified)
values-zh for Chinese(maybe simplified, traditional, hongkong and so on)

**Comment by ohmae** [comment]
Thanks. I didn't know that there were varieties in Chinese.

**Review by ohmae — APPROVED** [review]

**Pull request merged**
